server_site(z)/laravel/app/Http/routes.php
<?php
use App\Books;
use App\Author;
use App\Category;
use App\BookLevel;
use App\Publishers;
use App\DBPStatus;
use App\BooksImages;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\View;


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/login', 'HomeController@showLogin');
Route::post('/login','HomeController@doLogin');
Route::get('/register', 'HomeController@showRegister');
Route::post('/register', 'HomeController@toRegister');
Route::get('/verify/{token}','UsersAllController@verifyEmail');
Route::get('/password/change/{token}/proceed','UsersAllController@viewChangePassword');
Route::post('/password/change','UsersAllController@doChangePassword');

Route::filter('auth', function()
{
    if (Auth::guest()){
    	if(Request::is('api*')){
    		$msg = array('msg'=>'Please login');
    		return response()->json($msg)
        	->setCallback(Request::input('callback'));
    	}
    	return Redirect::to('login');
    } 
});




Route::filter('auth.basic', function()
{
    return Auth::basic();
});

Route::filter('guest', function()
{
    if (Auth::check()) return Redirect::to('dashboard');
});
Route::group(array('before' => 'auth'), function(){
    Route::resource('/', 'DashboardController');

    Route::resource('/dashboard',  'DashboardController');

    Route::resource('/books/book',  'BooksBookController');

    Route::get('/users/members',  'UsersAllController@index');

    Route::get('/users/admins',  'UsersAllController@adminIndex');

    Route::resource('/users/member',  'UsersAllController');

    Route::resource('/books/category',  'BooksCategoryController');

    Route::resource('/books/author',  'BooksAuthorController');

    Route::resource('/books/publisher',  'BooksPublisherController');

    Route::resource('/books/level', 'BooksLevelController');

    Route::get('/logout',  'HomeController@doLogout');

    Route::resource('/books/flipbook', 'FlipBookController');

    

});

//epub and pdf
Route::get('/downloads/book/{id}/{format}','BooksBookController@downloadBook'); //!!!!!!!!!!should be in session

// Route group for AJAX (SERVER-ADMIN) with auth
Route::group(array('prefix' => 'ajax','before'=>'auth'), function()
{
        //update sample upload
       Route::post('/book/{id}/uploadSample','BooksBookController@updateUploadSample');
       
       //delete all sample upload
       Route::get('/book/{id}/uploadSample/deleteAll','BooksBookController@deleteAllUploadedSample');

});


//MOBILE API
// open route
Route::group(array('prefix' => 'api/dbp'), function()
{

    Route::get('category/all', 'APIServiceController@category');
    Route::get('book/{id}', 'APIServiceController@bookDetails');

});



// Route with XHR handler
Route::group(array('middleware'=>'cors','prefix' => 'api/dbp'), function()
{
    Route::resource('login', 'APIServiceController@login');
    Route::resource('logout', 'APIServiceController@logout');
    Route::resource('register','APIServiceController@register');
    Route::get('password/forgot/{email}','APIServiceController@forgotPassword');

});

server_site(z)/laravel/app/Books.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Books extends Model {

	protected $table = 'dbp_books';

	public function authors()
    {
        return $this->belongsToMany('App\Author','dbp_books_dbp_authors','dbp_books_id','dbp_authors_author_id');
    }

    public function samples()
    {
    	return $this->hasMany('App\BooksImages','books_id');
    }

    public function categories()
    {
    	return $this->belongsToMany('App\Category','dbp_books_dbp_category','dbp_books_id','dbp_category_cat_id');
    }


}

server_site(z)/laravel/resources/views/books/author.blade.php
  <div class="pull-left breadcrumb_admin clear_both">
    <div class="pull-left page_title theme_color">
      <h1>Buku / Penulis</h1>
      <h2 class="">Senarai Penulis</h2>
    </div>
    <div class="pull-right">
      <ol class="breadcrumb">
        <li><a href="#">Buku</a></li>
        <li class="active">Penulis</li>
      </ol>
    </div>
  </div>
  <div class="container clear_both padding_fix"> 
    
    <div id="main-content">
      <div class="page-content">
      @if ( Session::has('flash_message') )
        <div class="alert {{ Session::get('flash_type') }}">
            <h3>{{ Session::get('flash_message') }}</h3>
        </div>
        
      @endif
                <!-- @if (Session::has('message'))
                <div class="alert alert-info">{{ Session::get('message') }}</div>
      @endif -->
        <div class="row">
         
           
            <div class="block-web col-md-8">
              <div class="header">

                <h3 class="content-header">Senarai Penulis</h3>
              </div>
              <div class="porlets-content ">
                <div class="adv-table editable-table ">
                  <div class="clearfix">
                    <div class="btn-group">
                      <button onclick="newAuthor()" class="btn btn-primary"> Tambah <i class="fa fa-plus"></i> </button>
                    </div>
                    
                  </div>
                  <div class="margin-top-10"></div>
                  <table class="table table-striped table-hover table-bordered " id="editable-sample">
                    <thead>
                      <tr>
                        <th>Author Name</th>
                        <th class="center">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                    
                    @foreach($author as $value)
                    <tr>
                      <td>{{ $value->author_name }}</td>
                      <td class="center">
                        {!! link_to_route('books.author.edit', 'Kemaskini', array($value->author_id),array('class' => 'btn btn-xs btn-info')) !!}
                        {!! Form::open(array('style' => 'display:inline-block','method'=> 'DELETE', 'url' =>array('books/author', $value->author_id))) !!}
                        {!! Form::submit('Padam', array('class' => 'btn btn-xs btn-danger')) !!}
                        {!! Form::close() !!}
                      </td>
                    </tr>
                    @endforeach
                    </tbody>
                    
                  </table>
                </div>
              </div>

            </div>

          </div>

        </div>

      </div>

    </div>

  </div>
<script>
function newAuthor(){
    window.location.href="{{ URL('books/author/create') }}";
}
</script>

server_site(z)/laravel/resources/views/books/book.blade.php
  <div class="pull-left breadcrumb_admin clear_both">
    <div class="pull-left page_title theme_color">
      <h1>Buku / Senarai Buku</h1>
      <h2 class="">Senarai Buku</h2>
    </div>
    <div class="pull-right">
      <ol class="breadcrumb">
        <li><a href="#">Buku</a></li>
        <li class="active">Senarai Buku</li>
      </ol>
    </div>
  </div>
  <div class="container clear_both padding_fix"> 
    
    <div id="main-content">
      <div class="page-content">

        <div class="row">
          <div class="col-md-12">@if (Session::has('message'))
<div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
    </div>
           
            <div class="block-web">
              <div class="header">
                <h3 class="content-header">Senarai Buku</h3>
              </div>
              <div class="porlets-content">
                <div class="adv-table editable-table ">
                  <div class="clearfix">
                    <div class="btn-group">
                      <button onclick="newBook()" class="btn btn-primary"> Tambah <i class="fa fa-plus"></i> </button>
                    </div>
                    <div class="btn-group pull-right">
                    
                    </div>
                  </div>
                  <div class="margin-top-10"></div>
                  <table class="table table-striped table-hover table-bordered" id="editable-sample">
                    <thead>
                      <tr>
                        <th>Tajuk</th>
                        <th>Penulis</th>
                        <th class="center">Harga(RM)</th>
                        
          
                        <th class="center" class="center" class="center" class="center">
                        Kategori
                        </th>
                        <th class="center" class="center" class="center" class="center">
                        Tindakan
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                    
                    @foreach($books as $value)
                    <tr>
                      <td>{{ $value->title }}</td>
                      <td>{{ implode(',',$value->authors)}}</td>
                      <td class="center">{{ number_format((float)$value->price, 2, '.', '') }}</td>
                      <td class="center">{{ implode(',',$value->categories)}}</td>
                      <td class="center">
                        {!! link_to_route('books.book.show', 'Lihat', array($value->id),array('class' => 'btn btn-xs btn-success','style'=>'margin-right:5px')) !!}
                        {!! link_to_route('books.book.edit', 'Kemaskini', array($value->id),array('class' => 'btn btn-xs btn-info','style'=>'margin-right:5px')) !!}
                        {!! Form::open(array('style' => 'display:inline-block','method'=> 'DELETE', 'url' =>array('books/book', $value->id))) !!}
                        {!! Form::submit('Padam', array('class' => 'btn btn-xs btn-danger')) !!}
                        {!! Form::close() !!}
                    </tr>
                    @endforeach
                    </tbody>
                    
                  </table>
                </div>
              </div>

            </div>

          </div>

        </div>

      </div>

    </div>

  </div>
<script>
function newBook(){
    window.location.href="{{ URL('books/book/create') }}";   
}

</script>

server_site(z)/laravel/resources/views/books/category.blade.php
  <div class="pull-left breadcrumb_admin clear_both">
    <div class="pull-left page_title theme_color">
      <h1>Buku / Kategori</h1>
      <h2 class="">Senarai Kategori</h2>
    </div>
    <div class="pull-right">
      <ol class="breadcrumb">
        <li><a href="#">Buku</a></li>
        <li class="active">Kategori</li>
      </ol>
    </div>
  </div>
  <div class="container clear_both padding_fix"> 
    
    <div id="main-content">
      <div class="page-content">

        <div class="row">
          <div class="col-md-12">@if (Session::has('message'))
<div class="flash alert">{{ Session::get('message') }}</div>
@endif
    </div>
           
            <div class="block-web">
              <div class="header">
                 <h3 class="content-header">Senarai Kategori</h3>
              </div>
              <div class="porlets-content">
                <div class="adv-table editable-table ">
                  <div class="clearfix">
                    <div class="btn-group">
                      <button onclick="newCategory()" class="btn btn-primary"> Tambah <i class="fa fa-plus"></i> </button>
                    </div>
                    <div class="btn-group pull-right">
                      
                    </div>
                  </div>
                  <div class="margin-top-10"></div>
                  <table class="table table-striped table-hover table-bordered" id="editable-sample">
                    <thead>
                      <tr>
                        <th>Category</th>
                        <th class="center">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                    
                    @foreach($category as $value)
                    <tr>
                      <td>{{ $value->category_name }}</td>
                      <td class="center">
                      {!! link_to_route('books.category.edit', 'Kemaskini', array($value->cat_id),
                                      array('class' => 'btn btn-xs btn-info')) !!}
                        {!! Form::open(array('style' => 'display:inline-block','method'=> 'DELETE', 'url' =>array('books/category', $value->cat_id))) !!}
                        {!! Form::submit('Padam', array('class' => 'btn btn-xs btn-danger')) !!}
                        {!! Form::close() !!}
                      </td>
                    </tr>
                    @endforeach
                    </tbody>
                    
                  </table>
                </div>
              </div>

            </div>

          </div>

        </div>

      </div>

    </div>

  </div>
<script>
function newCategory(){
    window.location.href="{{ URL('books/category/create') }}";
}
function updateBook(val){
      window.location.href="{{ URL('books/book') }}/"+val+"/edit";  
}
</script>

server_site(z)/laravel/resources/views/books/level.blade.php
  <div class="pull-left breadcrumb_admin clear_both">
    <div class="pull-left page_title theme_color">
      <h1>Buku / Peringkat</h1>
      <h2 class="">Senarai Semua Peringkat</h2>
    </div>
    <div class="pull-right">
      <ol class="breadcrumb">
        <li><a href="#">Buku</a></li>
        <li class="active">Peringkat</li>
      </ol>
    </div>
  </div>
  <div class="container clear_both padding_fix"> 
    
    <div id="main-content">
    @if ( Session::has('flash_message') )
      <div style="padding:5px;margin-bottom:0px;" class="alert {{ Session::get('flash_type') }}">
          <h3 style="font-size:20px;">{{ Session::get('flash_message') }}</h3>
      </div>
      
    @endif
      <div class="page-content">
      
                <!-- @if (Session::has('message'))
                <div class="alert alert-info">{{ Session::get('message') }}</div>
      @endif -->
        <div class="row">
          <div class="col-md-12">
          
    </div>
           
            <div class="block-web">
              <div class="header">
                <h3 class="content-header">Senarai Peringkat</h3>
              </div>
              <div class="porlets-content">
                <div class="adv-table editable-table ">
                  <div class="clearfix">
                    <div class="btn-group">
                      <button onclick="newlevel()" class="btn btn-primary"> Tambah <i class="fa fa-plus"></i> </button>
                    </div>
                    <div class="btn-group pull-right">
                      
                    </div>
                  </div>
                  <div class="margin-top-10"></div>
                  <table class="table table-striped table-hover table-bordered" id="editable-sample">
                    <thead>
                      <tr>
                        <th>Peringkat</th>
                        <th class="center">Tindakan</th>
                      </tr>
                    </thead>
                    <tbody>
                    
                    @foreach($level as $value)
                    <tr>
                      <td>{{ $value->level_name }}</td>
                      <td class="center">
                        {!! link_to_route('books.level.edit', 'Kemaskini', array($value->level_id),array('class' => 'btn btn-xs btn-info')) !!}
                        {!! Form::open(array('style' => 'display:inline-block','method'=> 'DELETE', 'url' =>array('books/level', $value->level_id))) !!}
                        {!! Form::submit('Padam', array('class' => 'btn btn-xs btn-danger')) !!}
                        {!! Form::close() !!}
                      </td>
                    </tr>
                    @endforeach
                    </tbody>
                    
                  </table>
                </div>
              </div>

            </div>

          </div>

        </div>

      </div>

    </div>

  </div>
<script>
function newlevel(){
    window.location.href="{{ URL('books/level/create') }}";
}
</script>

server_site(z)/laravel/resources/views/books/publisher.blade.php
  <div class="pull-left breadcrumb_admin clear_both">
    <div class="pull-left page_title theme_color">
      <h1>Books / Publisher</h1>
      <h2 class="">Display All Publisher</h2>
    </div>
    <div class="pull-right">
      <ol class="breadcrumb">
        <li><a href="#">Books</a></li>
        <li class="active">Publisher</li>
      </ol>
    </div>
  </div>
  <div class="container clear_both padding_fix"> 
    
    <div id="main-content">
    @if ( Session::has('flash_message') )
      <div style="padding:5px;margin-bottom:0px;" class="alert {{ Session::get('flash_type') }}">
          <h3 style="font-size:20px;">{{ Session::get('flash_message') }}</h3>
      </div>
      
    @endif
      <div class="page-content">
      
                <!-- @if (Session::has('message'))
                <div class="alert alert-info">{{ Session::get('message') }}</div>
      @endif -->
        <div class="row">
          <div class="col-md-12">
          
    </div>
           
            <div class="block-web">
              <div class="header">
                <h3 class="content-header">Senarai Penerbit</h3>
              </div>
              <div class="porlets-content">
                <div class="adv-table editable-table ">
                  <div class="clearfix">
                    <div class="btn-group">
                      <button onclick="newPublisher()" class="btn btn-primary"> Tambah <i class="fa fa-plus"></i> </button>
                    </div>
                    <div class="btn-group pull-right">
                      
                    </div>
                  </div>
                  <div class="margin-top-10"></div>
                  <table class="table table-striped table-hover table-bordered" id="editable-sample">
                    <thead>
                      <tr>
                        <th>Publisher Name</th>
                        <th class="center">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                    
                    @foreach($publisher as $value)
                    <tr>
                      <td>{{ $value->publisher_name }}</td>
                      <td class="center">
                        {!! link_to_route('books.publisher.edit', 'Update', array($value->pub_id),array('class' => 'btn btn-xs btn-info')) !!}
                        {!! Form::open(array('style' => 'display:inline-block','method'=> 'DELETE', 'url' =>array('books/publisher', $value->pub_id))) !!}
                        {!! Form::submit('Delete', array('class' => 'btn btn-xs btn-danger')) !!}
                        {!! Form::close() !!}
                      </td>
                    </tr>
                    @endforeach
                    </tbody>
                    
                  </table>
                </div>
              </div>

            </div>

          </div>

        </div>

      </div>

    </div>

  </div>
<script>
function newPublisher(){
    window.location.href="{{ URL('books/publisher/create') }}";
}
</script>